name: Pull request check

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '20.16'
      - name: Install dependencies
        run: npm ci
      - name: Prettier
        run: npm run lint:prettier
      - name: Typescript
        run: npm run lint:tsc
      - name: Gatsby Build
        run: npm run build
        env:
          NODE_ENV: production
          GATSBY_SRC_ROOT: src
          GATSBY_PRINT_CONFIG: true
          SITE_URL: ${{ secrets.SITE_URL }}
          DIRECTUS_URL: ${{ secrets.DIRECTUS_URL }}
          DIRECTUS_TOKEN: ${{ secrets.DIRECTUS_TOKEN }}
